version: 2

project_name: libra

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0

builds:
  - targets: [go_first_class]
    mod_timestamp: "{{ .CommitTimestamp }}"
    dir: ./cmd/libra
    flags:
      # trims path
      - -trimpath
    ldflags:
      - -s -w -extldflags '-static'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  name_template: "v{{ .Version }}"

dockers:
  - image_templates:
      [
        "ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-amd64",
      ]
    dockerfile: ./misc/docker/goreleaser/Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=AGPL-3.0
docker_manifests:
  - name_template: ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-amd64
  - name_template: ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-amd64
